name: Update Compatibility Table

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Generate Compatibility Table
        id: generate_table
        run: |
          python .github/scripts/generate_compatibility_table.py

      - name: Update README with Compatibility Table
        run: |
          TABLE_CONTENT=$(cat .github/scripts/compatibility_table.md)
          awk -v table="$TABLE_CONTENT" '
            BEGIN { found=0 }
            /<!--COMPATIBILITY_TABLE_START-->/ {
              found=1
              print
              print table
              next
            }
            /<!--COMPATIBILITY_TABLE_END-->/ { found=0 }
            !found { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add README.md -f  # Force add to ensure it's staged
          git commit -m "Update compatibility table in README" || echo "Nothing to commit"
          git push --force

