# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04  # Specify the OS
  tools:
    python: "3.10"  # Specify the Python version

sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file

python:
  install:
    - requirements: requirements.txt  # Specify the requirements file
