name: tree-sankey-visualizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - anyio=4.6.0
  - argon2-cffi=23.1.0
  - attrs=24.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli=1.1.0
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - contourpy=1.3.0
  - cycler=0.12.1
  - fonttools=4.54.1
  - freetype=2.12.1
  - h11=0.14.0
  - httpx=0.27.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - ipywidgets=8.1.5
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jupyter=1.1.1
  - jupyter_client=8.6.3
  - jupyterlab=4.2.5
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - libblas=3.9.0
  - libdeflate=1.22
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libpng=1.6.44
  - libsodium=1.0.20
  - lightgbm=4.5.0
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - numpy=2.1.2
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - pillow=10.4.0
  - plotly=5.24.1
  - pluggy=1.5.0
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pygments=2.18.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyparsing=3.1.4
  - pytest=8.3.3
  - python-dateutil=2.9.0
  - pytz=2024.1
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tomli=2.0.2
  - tornado=6.4.1
  - typing-extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - widgetsnbextension=4.0.13
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zstandard=0.23.0

