name: tree-sankey-visualizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - anyio
  - argon2-cffi
  - attrs
  - beautifulsoup4
  - bleach
  - brotli
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - contourpy
  - cycler
  - fonttools
  - freetype
  - h11
  - httpx
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipywidgets
  - jinja2
  - joblib
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyterlab
  - jupyterlab_widgets
  - kiwisolver
  - lightgbm
  - matplotlib-base
  - matplotlib-inline
  - numpy
  - openssl
  - packaging
  - pandas
  - pillow
  - plotly
  - pluggy
  - prompt-toolkit
  - psutil
  - pygments
  - pytest
  - python-dateutil
  - pytz
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - six
  - statsmodels
  - threadpoolctl
  - tomli
  - tornado
  - typing-extensions
  - tzdata
  - urllib3
  - wheel
  - widgetsnbextension
