name: Continuous Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10.10
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install Publishing Tools
      run: |
        conda install setuptools wheel twine

    - name: Build and Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

