name: Continuous Integration

on:
  push:
    branches: [main, feature/testing-ci]
  pull_request:
    branches: [main, feature/testing-ci]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    # Remove potential cache for a fresh environment setup
    - name: Remove Conda Cache
      run: rm -rf /Users/runner/miniconda3/envs/test

    # Set up Conda and environment
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
        environment-file: environment.yml
        activate-environment: test  # Name of the environment in environment.yml
        auto-activate-base: false

    # Confirm Conda environment details for troubleshooting
    - name: Check Conda Info and Logs
      run: |
        conda info
        conda list
        conda config --show-sources

    - name: Run Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src  # Add the src directory to PYTHONPATH
        conda run -n test pytest
