name: Continuous Integration

on:
  push:
    branches: [main, testing-ci]
  pull_request:
    branches: [main, testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']  # Ensures correct versions

    steps:
    - uses: actions/checkout@v3

    # Set up Conda with Mamba for faster dependency resolution
    - name: Set up Conda with Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "${{ matrix.python-version }}"
        environment-file: environment.yml
        auto-activate-base: false
        use-mamba: true  # Uses Mamba for faster dependency resolution

    # Check Conda environment setup for troubleshooting
    - name: Confirm Conda Info and Environment
      run: |
        conda info
        conda list
        conda env list

    # Install pip dependencies explicitly
    - name: Install Pip Dependencies
      run: |
        conda activate test
        pip install tox pytest

    # Install the src package in editable mode
    - name: Install src package in editable mode
      run: |
        conda activate test
        pip install -e .

    # Run tests
    - name: Run Tests
      run: |
        conda activate test
        pytest
