name: Continuous Integration

on:
  push:
    branches: [main, testing-ci]
  pull_request:
    branches: [main, testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']  # Ensures correct versions

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda with Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "${{ matrix.python-version }}"
        auto-activate-base: false
        use-mamba: true

    - name: Remove Existing Environment
      run: conda env remove --name test || true

    - name: Debug Environment File
      run: cat environment.yml

    - name: Create Conda Environment
      run: conda env create --file environment.yml --verbose

    - name: Install Pip Dependencies
      run: |
        conda activate test
        pip install tox pytest

    - name: Install src package in editable mode
      run: |
        conda activate test
        pip install -e .

    - name: Run Tests
      run: |
        conda activate test
        pytest
