name: Continuous Integration

on:
  push:
    branches: [main, testing-ci]
  pull_request:
    branches: [main, testing-ci]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']  # Test with one version to simplify debugging

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda with Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "${{ matrix.python-version }}"
        environment-file: environment.yml
        auto-activate-base: false
        use-mamba: true

    - name: Debug Environment File
      run: cat environment.yml

    - name: Create Conda Environment
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda env create --file environment.yml --verbose

    - name: Install Pip Dependencies
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate test
        pip install tox pytest

    - name: Run Tests
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate test
        pytest
