name: Continuous Integration

on:
  push:
    branches: [ main, feature/testing-ci ]
  pull_request:
    branches: [ main, feature/testing-ci ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        auto-activate-base: false
        miniconda-version: "latest"

    - name: Install Dependencies
      run: |
        conda install pytest
        conda install --file requirements.txt  # If additional requirements exist

    - name: Run Tests
      run: |
        pytest
